// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.cmc.repo;

import com.cmc.domain.Issues;
import com.cmc.repo.IssuesRepository;
import java.util.List;

privileged aspect IssuesRepository_Roo_Finder {
    
    public abstract List<Issues> IssuesRepository.findByDoneRatioEquals(int doneRatio);    
}
